name: Infrastructure CI/CD

on:
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'mlops-course-04/terraform/**'
  workflow_dispatch:

jobs:
  terraform-plan-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mlops-course-04/terraform
    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Verify ECR Image Exists
        run: |
          REPO_NAME="ecr-mlops-course-ehb-repository9129-dev"
          IMAGE_DETAILS=$(aws ecr describe-images \
            --repository-name $REPO_NAME \
            --query 'imageDetails[0]')
          
          if [ -z "$IMAGE_DETAILS" ] || [ "$IMAGE_DETAILS" == "null" ]; then
            echo "::error::ECR image not found in repository $REPO_NAME"
            exit 1
          fi
          echo "ECR image verified successfully"

      - name: Terraform Init
        run: terraform init --backend-config='backends/dev.conf'

      - name: Terraform Format
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color --var-file='environments/dev.tfvars' -out=plan.tfout
      
      - name: Approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        with:
          secret: ${{ github.token }}
          approvers: rjncit
          issue-title: "Deploy Terraform Plan to dev"
          issue-body: "Please review the Terraform Plan"
          exclude-workflow-initiator-as-approver: false

      - name: Verify IAM Role (Pre-Apply)
        run: |
          # Get role name from plan output
          ROLE_NAME=$(terraform show -json plan.tfout | jq -r '.planned_values.root_module.resources[] | select(.type=="aws_iam_role") | .values.name')
          
          if [ -z "$ROLE_NAME" ]; then
            echo "::warning::No IAM role found in Terraform plan"
            exit 0
          fi
          
          echo "Verifying IAM role: $ROLE_NAME"
          
          # Check if role exists (should not exist before apply)
          if aws iam get-role --role-name $ROLE_NAME 2>/dev/null; then
            echo "::error::IAM role $ROLE_NAME already exists"
            exit 1
          fi
          echo "IAM role verification passed (role does not exist yet)"

      - name: Terraform Apply
        run: terraform apply -auto-approve plan.tfout

      - name: Verify IAM Role (Post-Apply)
        run: |
          # Get role name from state
          ROLE_NAME=$(terraform show -json | jq -r '.values.root_module.resources[] | select(.type=="aws_iam_role") | .values.name')
          
          if [ -z "$ROLE_NAME" ]; then
            echo "::error::No IAM role found in Terraform state"
            exit 1
          fi
          
          echo "Verifying IAM role after creation: $ROLE_NAME"
          
          # Verify role exists and has policies
          if ! aws iam get-role --role-name $ROLE_NAME; then
            echo "::error::IAM role $ROLE_NAME not found after creation"
            exit 1
          fi
          
          echo "Attached policies:"
          aws iam list-attached-role-policies --role-name $ROLE_NAME
          
          echo "Inline policies:"
          aws iam list-role-policies --role-name $ROLE_NAME
          echo "IAM role verification successful"