name: Infrastructure CI/CD

on:
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'mlops-course-04/terraform/**'
  workflow_dispatch:

jobs:
  terraform-plan-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mlops-course-04/terraform
    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Verify ECR Image Exists
        id: verify_ecr
        run: |
          REPO_NAME="ecr-mlops-course-ehb-repository9129-dev"
          IMAGE_DETAILS=$(aws ecr describe-images \
            --repository-name $REPO_NAME \
            --query 'imageDetails[0]')
          
          if [ -z "$IMAGE_DETAILS" ] || [ "$IMAGE_DETAILS" == "null" ]; then
            echo "::error::ECR image not found in repository $REPO_NAME"
            exit 1
          fi
          
          echo "ECR image verified successfully"
          echo "imageDigest=$(echo $IMAGE_DETAILS | jq -r '.imageDigest')" >> $GITHUB_OUTPUT

      - name: Verify IAM Permissions
        run: |
          # Get the expected role name from Terraform locals
          ROLE_NAME=$(terraform output -json | jq -r '.data.value.service_name + "-iam-role"')
          
          # Check if role exists
          aws iam get-role --role-name $ROLE_NAME
          
          # Check attached policies
          aws iam list-attached-role-policies --role-name $ROLE_NAME
          
          # Check inline policies
          aws iam list-role-policies --role-name $ROLE_NAME

      - name: Terraform Format
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init --backend-config='backends/dev.conf'

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color --var-file='environments/dev.tfvars' -out=plan.tfout
      
      - name: Approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        with:
          secret: ${{ github.token }}
          approvers: rjncit
          issue-title: "Deploy Terraform Plan to dev"
          issue-body: "Please review the Terraform Plan"
          exclude-workflow-initiator-as-approver: false

      - name: Terraform Apply
        run: terraform apply -auto-approve plan.tfout